name: 'CI (AetheryteLinkInChat)'

on:
  push:
    paths:
      - 'AetheryteLinkInChat/**'
    tags:
      - 'v*'
    branches:
      - 'master'

  pull_request:
    paths:
      - 'AetheryteLinkInChat/**'
    types:
      - opened
      - synchronize

  release:
    types:
      - created

  workflow_dispatch:

jobs:
  build:
    uses: SlashNephy/Divination/.github/workflows/reusable-build-plugin.yml@master
    with:
      plugin-name: 'AetheryteLinkInChat'
      working-directory: 'AetheryteLinkInChat'
    permissions:
      contents: read
      actions: write

  release:
    name: 'Create GitHub Release'
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: 'AetheryteLinkInChat'
          path: 'artifact'

      - name: Zip Plugin
        run: |
          Compress-Archive -Path artifact\* -DestinationPath AetheryteLinkInChat-Release.zip -Force

      - name: Create Release
        id: create_release
        uses: actions/create-release@0b499d523a91e9042525e3b367de3b4c2c4e6c9d # v1.14.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@5a3c4bf7395b47748cfe5b3571c463afc8f6e9cf # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: AetheryteLinkInChat-Release.zip
          asset_name: AetheryteLinkInChat-Release.zip
          asset_content_type: application/zip

  deploy:
    if: github.event_name != 'pull_request'
    needs: build
    uses: SlashNephy/Divination/.github/workflows/reusable-deploy-plugin.yml@master
    with:
      plugin-name: 'AetheryteLinkInChat'
    secrets:
      DEPLOY_GITHUB_TOKEN: '${{ secrets.DEPLOY_GITHUB_TOKEN }}'
    permissions:
      actions: read
